# This workflow pulls the ubuntu:jammy image and sets up the necessary tools for OpenWRT build

env:
  DK_IMAGE_NAME: "openwrt-buildenv"
  DK_REGISTRY: ${{secrets.docker_registry}}
  DK_USERNAME: ${{secrets.docker_username}}
  DK_PASSWORD: ${{secrets.docker_password}}
  TMATE_ENCRYPT_PASSWORD: ${{secrets.TMATE_ENCRYPT_PASSWORD}}

name: Build OpenWRT BuildEnv Docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - ".github/workflows/build.yml"
      - "scripts/upload-docker.sh"
      - "Dockerfile"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build-Docker-Iamge:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build Docker
        id: build
        continue-on-error: true
        run: docker build -t ${{env.DK_IMAGE_NAME}} . && echo ::set-output name=status::success

      - name: Commit Built Docker
        id: commit
        continue-on-error: true
        if: steps.build.outputs.status == 'success'
        run: bash -x scripts/upload-docker.sh && echo ::set-output name=status::success

      - name: "[Debug] Wait for SSH connection (timeout 5min)"
        if: steps.build.outputs.status != 'success' || steps.commit.outputs.status != 'success'
        env:
          TIMEOUT_MIN: 5
        uses: tete1030/safe-debugger-action@dev
